version: "3.1"

services:

  nginx:
    image: nginx:1.23-alpine
    container_name: godaddy_test_nginx
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
    ports:
      - "8088:80"
    networks:
      - godaddy_test_network

  fpm:
    build: ./php-fpm
    container_name: godaddy_test_fpm
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
    entrypoint: /code/.docker/php-fpm/entrypoint.sh
    links:
      - mysql
    networks:
      - godaddy_test_network
      - godaddy_test_db

  mysql:
    image: mysql:8.0.32
    container_name: godaddy_test_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=godaddy_test_db
    ports:
      - "3308:3306"
    networks:
      - godaddy_test_db

networks:
  godaddy_test_network:
    external: true
  godaddy_test_db:
    external: true
